/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

import org.junit.Test;
import static org.junit.Assert.*;

import org.junit.After;
import org.junit.Before;

public class NumeroRacionalTest {
    NumeroRacional n1;
    NumeroRacional n2;
    NumeroRacional n4;
    /**
     * Default constructor for test class NumeroRacionalTest
     */
    public NumeroRacionalTest()
    {
    }

    /**
     * Sets up the test fixture.
     *
     * Called before every test case method.
     */
    @Before
    public void setUp()
    {
        n1 = new NumeroRacional(1,2);
        n2 = new NumeroRacional(2,3);
        n4 = new NumeroRacional(2,4);
    }

    /**
     * Tears down the test fixture.
     *
     * Called after every test case method.
     */
    @After
    public void tearDown()
    {
    }
    
    @Test
    public void testConstructor()
    {        
        assertEquals(n1.getNumerador(), 1);
        assertEquals(n1.getDenominador(), 2);
    }
    
    @Test
    public void testSum(){
        NumeroRacional n3 = n1.sum(n2);
        assertEquals(n3.getNumerador(), 7);
        assertEquals(n3.getDenominador(), 6);
    }
    
    @Test 
    public void testSub(){
        NumeroRacional n3 = n1.sub(n2);
        assertEquals(n3.getNumerador(), -1);
        assertEquals(n3.getDenominador(), 6);
    }

    @Test
    public void testMultiplication(){
        NumeroRacional n3 = n1.mul(n2);
        assertEquals(2, n3.getNumerador());
        assertEquals(6, n3.getDenominador());
    }

    @Test
    public void testDivision(){
        NumeroRacional n3 = n1.div(n2);
        assertEquals(3, n3.getNumerador());
        assertEquals(4, n3.getDenominador());
    }

    @Test
    public void testSimplify(){
        NumeroRacional n3 = n4.simplify();
        assertEquals(1, n3.getNumerador());
        assertEquals(2, n3.getDenominador());
    }

    @Test
    public void testToFloat(){
        assertEquals(0.5, n1.toFloat(), 0.00001);        
        assertEquals(0.6666, n2.toFloat(), 0.0001);
    }

}
